name: Create Markdown File

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  create-meeting-minutes:

    runs-on: ubuntu-latest

    steps:
    - uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "docs/DateTime<'Y-m-d H:i:s'>.md"
        FILE_DATA: "### file content \n testing content"
