# name: Create Markdown File
# on:
#   schedule:
#   - cron: "*/5 * * * *"

# jobs:
#   create-meeting-minutes:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: finnp/create-file-action@1.0.0
#       env:
#         FILE_NAME: "docs/DateTime<'Y-m-d H:i:s'>.md"
#         FILE_DATA: "### file content \n testing content"

# This is a basic workflow to help you get started with Actions

name: Create Markdown File

# Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string.
#     # /30 denotes that it will run once every 30 minutes
#     - cron:  '*/5 * * * *'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  create-meeting-minutes:
    
    runs-on: ubuntu-latest

    steps:
    - uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "DateTime<'Y-m-d H:i:s'>.md"
        FILE_DATA: "### file content \n testing content"
        
    - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'src'

#         # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
#         # Default: '.'
#         cwd: './path/to/the/repo'

        # The message for the commit
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'docs:Add markdown'

        # The flag used on the pull strategy
        # Default: '--no-rebase'
        pull_strategy: '--no-rebase or --no-ff or --rebase'


        # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
        # Default: ''
        tag: 'v1.0.0 --force'

